name: ci

on:
  push:
    branches:
      - 'master'
      - 'main'
      - 'actions'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Branch name
        id: branch_name
        run: |
          echo ::set-output name=SOURCE_NAME::${GITHUB_REF#refs/*/}
          echo ::set-output name=SOURCE_BRANCH::${GITHUB_REF#refs/heads/}
          echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}
          
      - name: Sync - Build and push
        id: docker_build_sync
        uses: docker/build-push-action@v2
        with:
          file: ./vscoffline/vscsync/Dockerfile          
          tags: lolinternet/vscsync:actions,lolinternet/vscsync:${{ steps.branch_name.outputs.SOURCE_TAG }}
          push: true
          
      - name: Sync - Build and push
        id: docker_build_gallery
        uses: docker/build-push-action@v2
        with:
          file: ./vscoffline/vscgallery/Dockerfile
          tags: lolinternet/vscgallery:actions,lolinternet/vscgallery:${{ steps.branch_name.outputs.SOURCE_TAG }}
          push: true
