name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get version
        id: get_version
        uses: battila7/get-version-action@v2
          
      - name: Sync - Build and push
        id: docker_build_sync
        uses: docker/build-push-action@v2
        with:
          file: ./vscoffline/vscsync/Dockerfile          
          tags: lolinternet/vscsync:actions,lolinternet/vscsync:${{ steps.get_version.outputs.version-without-v }}
          push: true
          
      - name: Sync - Build and push
        id: docker_build_gallery
        uses: docker/build-push-action@v2
        with:
          file: ./vscoffline/vscgallery/Dockerfile
          tags: lolinternet/vscgallery:actions,lolinternet/vscgallery:${{ steps.get_version.outputs.version-without-v }}
          push: true
